### PR TITLE
Android 12+ service restart bug fix

### PR DESCRIPTION
**Pull request by GransonO**
Added a patch for restarting the service on app destroy

### CODE REVIEW

**Review by jgkiano — CHANGES_REQUESTED** [review]
Hey @GransonO [this](https://github.com/OkHi/android-background-geofencing/blob/6c5c25b6bb6830d25e9ba7bc68b33525dcc7b1d0/android-background-geofencing/src/main/java/io/okhi/android_background_geofencing/BackgroundGeofencing.java#L87C70-L87C99) method should indicate throwing an Exception rather than the BGException

**Comment by jgkiano** [comment]
Any permission requirements to run this? Also how can we determine that the service was started due to the alarm manager?

**Comment by GransonO** [comment]
> Any permission requirements to run this? Also how can we determine that the service was started due to the alarm manager?

We are working with the alarm set() function which requires no permissions to be added as opposed to setExact(). This is a minimum patch as there is no other official Android-Approved method as of now.

**Comment by GransonO** [comment]
> Hey @GransonO [this](https://github.com/OkHi/android-background-geofencing/blob/6c5c25b6bb6830d25e9ba7bc68b33525dcc7b1d0/android-background-geofencing/src/main/java/io/okhi/android_background_geofencing/BackgroundGeofencing.java#L87C70-L87C99) method should indicate throwing an Exception rather than the BGException

We might not need to change the exception type for all instances of the startforeground functions, rather only have it on the instance which is called in the background. The rest should throw the BGException as they are utilized when the app is in the foreground.
Lemme run more tests to approve this.

**Comment by jgkiano** [comment]
> Hey @GransonO [this](https://github.com/OkHi/android-background-geofencing/blob/6c5c25b6bb6830d25e9ba7bc68b33525dcc7b1d0/android-background-geofencing/src/main/java/io/okhi/android_background_geofencing/BackgroundGeofencing.java#L87C70-L87C99) method should indicate throwing an Exception rather than the BGException

If you want it to still throw a BGException you could wrap `ContextCompat.startForegroundService(context, serviceIntent);` in a try catch and transform the error to a BGException before throwing

```java
try {
  ContextCompat.startForegroundService(context, serviceIntent);
  BackgroundGeofenceUtil.scheduleForegroundRestartWorker(context, 1, TimeUnit.HOURS);
} catch (Exception e) {
  throw new BackgroundGeofencingException(...)
}
```

**Review by jgkiano — APPROVED** [review]
LGTM!

**Pull request merged**
